import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import Provider from "./provider";
import { Toast } from "radix-ui";
import { Toaster } from "@/components/ui/sonner";
const AppFont = DM_Sans({
  subsets: ['latin']

})
export const metadata: Metadata = {
  title: "Ai video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
       className={AppFont.className} 
      >
        <Provider>{children}</Provider>
        <Toaster position="top-center"  richColors/>
      </body>
    </html>
    </ClerkProvider>
  );
}
